config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"

  get "profile" => "users#profile", as: :profile
  get "profile/edit" => "users#edit_profile", as: :edit_profile
  get "users/:id/profile" => "users#public_profile", as: :public_profile
  post "users/:id/follow" => "users#follow", as: :follow_user
  delete "users/:id/unfollow" => "users#unfollow", as: :unfollow_user

  # photos routes
  get "photos/feed" => "photos#feed", as: :photos_feed
  get "photos/discovery" => "photos#discovery", as: :photos_discovery

  # albums routes
  get "albums/feed" => "albums#feed", as: :albums_feed
  get "albums/discovery" => "albums#discovery", as: :albums_discovery

  resources :albums, only: [ :index, :new, :create, :edit, :update, :destroy ]
  resources :photos, only: [ :index, :new, :create, :edit, :update, :destroy ]
  resources :users, only: [ :index, :create, :new, :update ]

  namespace :admin do
    root "photos#index"
    resources :photos, only: [ :index, :edit, :update ]
    resources :albums, only: [ :index, :edit, :update ]
    resources :users, only: [ :index, :edit, :update, :destroy ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :omniauthable, omniauth_providers: [ :google_oauth2, :facebook, :twitter ]
  enum :role, { user: 0, admin: 1 }, prefix: true
  enum :status, { active: 0, inactive: 1 }, prefix: true

  mount_uploader :avatar, AvatarUploader

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  # Override Devise method to prevent inactive users from signing in
  def active_for_authentication?
    super && status_active?
  end

  def self.from_omniauth(auth)
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    return user if user

    email = auth.info.email
    user = User.find_or_initialize_by(email: email)
    user.provider = auth.provider
    user.uid      = auth.uid
    user.firstName = auth.info.first_name || "User" if user.firstName.blank?
    user.lastName  = auth.info.last_name  || "Name"  if user.lastName.blank?
    user.password = Devise.friendly_token[0, 20] if user.new_record?

    # Skip email confirmation for OAuth users since the provider already verified the email
    user.skip_confirmation! if user.respond_to?(:skip_confirmation!)

    user.save!
    user
  end

  # Custom message for inactive users
  def inactive_message
    status_inactive? ? :inactive_account : super
  end

  # Associations for follows
  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followed

  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower

  # Association for photos
  has_many :photos
  # Association for albums
  has_many :albums

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :firstName, presence: true
  validates :lastName, presence: true
  scope :role_user, -> { where(role: :user) }
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :set_user, only: %i[ destroy edit update ]
    before_action :authorize_admin!
    def index
      @pagy, @users = pagy(User.role_user.order(created_at: :desc), limit: 10)
    end

    def edit
    end

    def update
      if @user.update(user_params)
        if @user.status_previously_changed? && @user.status == "inactive"
          UserMailer.inactive_mail(@user).deliver_now
        end
        redirect_to admin_users_path, notice: "Update user successfully!"
      else
        render :edit
      end
    end

    def destroy
      if @user.destroy
        UserMailer.delete_mail(@user).deliver_now
        redirect_to admin_users_path, notice: "Delete user successfully!"
      else
        redirect_to admin_users_path, notice: "Failed to delete user."
      end
    end

    private
      def set_user
        @user = User.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def user_params
        # params.expect(user: [ :firstName, :lastName, :email, :avatar ])
        params.require(:user).permit(:firstName, :lastName, :email, :avatar, :status)
      end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    handle_auth "Google"
  end

  def facebook
    handle_auth "Facebook"
  end

  def twitter
    handle_auth "X"
  end

  def failure
    redirect_to root_path
  end

  def handle_auth(kind)
    auth = request.env["omniauth.auth"]
    @user = User.from_omniauth(auth)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
    else
      session["devise.omniauth_data"] = auth.except("extra")
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [ :create ]
  # layout "auth"
  before_action :configure_account_update_params, only: [ :update ]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

    update_params = account_update_params
    if update_params[:current_password].present? && (update_params[:password].blank? || update_params[:password_confirmation].blank?)
      redirect_to edit_profile_path,
                  alert: "Password and confirmation can't be blank",
                  status: :see_other
      return
    end

    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
    resource_updated = update_resource(resource, update_params)

    if resource_updated
      yield resource if block_given?
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name
      redirect_to profile_path, notice: "Password updated", status: :see_other
    else
      message = resource.errors.full_messages.to_sentence
      redirect_to edit_profile_path,
                  alert: (message.present? ? message : "Password update failed"),
                  status: :see_other
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :firstName, :lastName ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [ :password, :password_confirmation, :current_password ])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [ :create ]
  # layout 'auth'

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super do |user|
      user.update_column(:last_sign_in_at, Time.current)
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [ :email, :password, :remember_me ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[update ]
  before_action :authorize_user_edit!, only: %i[update ]

  # GET /profile
  def profile
    @user = current_user
    @is_my_profile = true
    @active_tab = params[:tab] || "photos"
    render :profile
  end

  # GET /profile/edit
  def edit_profile
    @user = current_user
    render :edit_profile
  end

  # GET /users/:id/profile
  def public_profile
    @user = User.find(params[:id])
    if @user == current_user
      @is_my_profile = true
    else
      @is_my_profile = false
    end
    @active_tab = params[:tab] || "photos"
    render :profile
  end

  # POST /users/:id/follow
  def follow
    @user = User.find(params[:id])
    unless current_user == @user || current_user.following.include?(@user)
      current_user.following << @user
    end
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to request.referer, notice: "You are now following #{@user.firstName}" }
    end
  end

  # DELETE /users/:id/unfollow
  def unfollow
    @user = User.find(params[:id])
    current_user.following.delete(@user)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to request.referer, notice: "You have unfollowed #{@user.firstName}" }
    end
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to profile_path, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :profile, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def authorize_user_edit!
      return if current_user.role_admin? || @user == current_user

      redirect_to profile_path, alert: "Not authorized"
    end

    # Only allow a list of trusted parameters through.
    def user_params
      # params.expect(user: [ :firstName, :lastName, :email, :avatar ])
      params.require(:user).permit(:firstName, :lastName, :email, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    if user.avatar.blank?
      "https://ui-avatars.com/api/?name=#{user.firstName}+#{user.lastName}&size=256"
    else
      user.avatar.url
    end
  end
end

app/views/users/_follow_button.html.erb
<div class="follow-button-user-<%= user.id %> d-inline">
  <% if current_user && current_user != user %>
    <% if current_user.following.include?(user) %>
      <%= button_to "Unfollow", unfollow_user_path(user), method: :delete, class: "btn btn-outline-secondary btn-cus rounded-pill", data: { turbo_prefetch: false } %>
    <% else %>
      <%= button_to "Follow", follow_user_path(user), method: :post, class: "btn btn-primary btn-cus rounded-pill", data: { turbo_prefetch: false } %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, html: { class: "d-flex flex-column align-items-center" }) do |form| %>
  <div class="avatar mb-3 position-relative" data-controller="image-preview">
    <label for="avatar-input" style="cursor: pointer; display: block; width: 100%; height: 100%;">
      <%= image_tag avatar_url(user), class: "object-fit-cover rounded-2 w-100 h-100", alt: "Profile Avatar", data: { image_preview_target: "output" } %>
    </label>
    <%= form.file_field :avatar, id: "avatar-input", class: "d-none", accept: "image/*", data: { image_preview_target: "input", action: "change->image-preview#preview" } %>
  </div>
  <h2 class="fw-bold fs-6 text-primary">Basic Information</h2>
  <div class="mb-1 d-flex flex-column align-items-start">
    <%= form.label :firstName %>
    <%= form.text_field :firstName, class: "form-control", autofocus: true %>
  </div>

  

  <div class="mb-1 d-flex flex-column align-items-start">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, class: "form-control" %>
  </div>

  <div class="mb-1 d-flex flex-column align-items-start">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>


  <div>
    <%= form.submit class: "btn btn-success mt-3", value: "Save" %>
  </div>
<% end %>

app/views/users/_form_password.html.erb
<%= form_with(model: user, url: registration_path(:user), method: :patch, data: { turbo: false }, html: { class: "d-flex flex-column align-items-center mt-5" }) do |form| %>
  <h2 class="fw-bold fs-6 text-primary">Password</h2>

  <div class="mb-1 d-flex flex-column align-items-start">
    <%= form.label :current_password %>
    <%= form.password_field :current_password, class: "form-control" %>
  </div>

  <div class="mb-1 d-flex flex-column align-items-start">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", autofocus: true %>
  </div>
  

  <div class="mb-1 d-flex flex-column align-items-start">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-success mt-3", value: "Save" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="col mt-3">
  <div class="card text-center shadow-sm border-0 p-4">
    <div class="d-flex justify-content-center mt-3">
      <%= image_tag avatar_url(user), class: "rounded-circle object-fit-cover", style: "width: 120px; height: 120px", alt: "avatar" %>
    </div>
    <div class="card-body">
      <h5 class="card-title fw-bold mb-3"><%= user.firstName %> <%= user.lastName %></h5>
      <div class="d-flex justify-content-evenly mb-3">
        <div class="text-center">
          <h6 class="fw-bold mb-0"><%= user.photos_count %></h6>
          <small class="text-muted">Photos</small>
        </div>
        <div class="text-center">
          <h6 class="fw-bold mb-0"><%= user.albums_count %></h6>
          <small class="text-muted">Albums</small>
        </div>
      </div>
        <%= render partial: "users/follow_button", locals: { user: user } %>
    </div>
  </div>
</div>

app/views/users/edit_profile.html.erb
<% content_for :styles do %>
    <%= stylesheet_link_tag "edit_user", "data-turbo-track": "reload" %>
<% end %>

<div class="form-content">
    <%= render "form", user: @user %>
    <%= render "form_password", user: @user %>
</div>

app/views/users/follow.turbo_stream.erb
<turbo-stream action="replace" targets=".follow-button-user-<%= @user.id %>">
  <template>
    <%= render partial: "users/follow_button", formats: [:html], locals: { user: @user } %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="followers-count-<%= @user.id %>">
  <template>
    <%= @user.followers.size %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="followings-count-<%= current_user.id %>">
  <template>
    <%= current_user.following.size %>
  </template>
</turbo-stream>

app/views/users/profile.html.erb
<div
  class="content d-flex flex-column flex-md-row w-100 align-items-center text-center text-md-start"
>
  <div
    class="col-md-3 d-flex flex-column align-items-center mb-4 mb-md-0 me-md-4"
  >
    <%= image_tag avatar_url(@user), class: "rounded-circle object-fit-cover", style: "width: 120px; height: 120px", alt: "Profile Avatar" %>
  </div>
  <div class="w-100">
    <div
      class="d-flex align-items-center justify-content-center justify-content-md-start mb-2"
    >
    <% if @is_my_profile %>
      <%= link_to "Edit Profile", edit_profile_path, class: "btn btn-outline-primary btn-sm rounded-pill px-3 fw-bold", data: { turbo_prefetch: false } %>
    <% else %>
      <%= render partial: "users/follow_button", locals: { user: @user } %>
    <% end %>
    </div>
    <h1 class="fw-bold mb-2"><%= @user.firstName + " " + @user.lastName %></h1>
    <% photos_tab_path = @is_my_profile ? profile_path(tab: "photos") : public_profile_path(@user, tab: "photos") %>
    <% albums_tab_path = @is_my_profile ? profile_path(tab: "albums") : public_profile_path(@user, tab: "albums") %>
    <% followings_tab_path = @is_my_profile ? profile_path(tab: "followings") : public_profile_path(@user, tab: "followings") %>
    <% followers_tab_path = @is_my_profile ? profile_path(tab: "followers") : public_profile_path(@user, tab: "followers") %>
    <div
      class="d-flex flex-wrap justify-content-center justify-content-md-start gap-3 gap-md-4 text-secondary"
    >
      <%= link_to photos_tab_path, class: "text-decoration-none", data: { turbo_prefetch: false } do %>
        <% count_photos = @is_my_profile ? @user.photos.size : @user.photos.public_photos.size %>
        <span class="fw-bold text-dark fs-5"><%= count_photos %></span>
        <span class="small text-secondary">PHOTOS</span>
      <% end %>
      <%= link_to albums_tab_path, class: "text-decoration-none", data: { turbo_prefetch: false } do %>
        <% count_albums = @is_my_profile ? @user.albums.size : @user.albums.public_albums.size %>
        <span class="fw-bold text-dark fs-5"><%= count_albums %></span>
        <span class="small text-secondary">ALBUMS</span>
      <% end %>
      <%= link_to followings_tab_path, class: "text-decoration-none", data: { turbo_prefetch: false } do %>
        <span class="fw-bold text-dark fs-5" id="followings-count-<%= @user.id %>"><%= @user.following.size %></span>
        <span class="small text-secondary">FOLLOWINGS</span>
      <% end %>
      <%= link_to followers_tab_path, class: "text-decoration-none", data: { turbo_prefetch: false } do %>
        <span class="fw-bold text-dark fs-5" id="followers-count-<%= @user.id %>"><%= @user.followers.size %></span>
        <span class="small text-secondary">FOLLOWERS</span>
      <% end %>
    </div>
  </div>
</div>

<% if @is_my_profile %>
  <% if @active_tab == "albums" %>
    <%= link_to "Add album", new_album_path, class: "mt-5 align-self-md-end align-self-center btn btn-success rounded-pill btn-add-photos", data: { turbo_prefetch: false } %>
  <% else %>
    <%= link_to "Add photos", new_photo_path, class: "mt-5 align-self-md-end align-self-center btn btn-success rounded-pill btn-add-photos", data: { turbo_prefetch: false } %>
  <% end %>
<% end %>

<%# body content here %>
<div
  class="row row-cols-lg-3 row-cols-md-2 row-cols-xl-4 row-cols-1 mt-5"
>
  <% case @active_tab %>
  <% when "albums" %>
    <% query_for_albums = @is_my_profile ? @user.albums.includes(:photos) : @user.albums.public_albums.includes(:photos) %>
    <%= render partial: "albums/album_item", collection: query_for_albums, as: :album, locals: { is_my_profile: @is_my_profile } %>
  <% when "photos" %>
    <% query_for_photos = @is_my_profile ? @user.photos : @user.photos.public_photos %>
    <%= render partial: "photos/photo_item", collection: query_for_photos, as: :photo, locals: { is_my_profile: @is_my_profile } %>
  <% when "followings" %>
    <%= render partial: "user", collection: @user.following, as: :user, locals: { is_my_profile: @is_my_profile } %>
  <% when "followers" %>
    <%= render partial: "user", collection: @user.followers, as: :user, locals: { is_my_profile: @is_my_profile } %>
  <% end %>
</div>


<%= render 'photos/photo_modal' %>
<%= render 'albums/album_modal' %>

app/views/users/unfollow.turbo_stream.erb
<turbo-stream action="replace" targets=".follow-button-user-<%= @user.id %>">
  <template>
    <%= render partial: "users/follow_button", formats: [:html], locals: { user: @user } %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="followers-count-<%= @user.id %>">
  <template>
    <%= @user.followers.size %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="followings-count-<%= current_user.id %>">
  <template>
    <%= current_user.following.size %>
  </template>
</turbo-stream>