config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"

  get "profile" => "users#profile", as: :profile
  get "profile/edit" => "users#edit_profile", as: :edit_profile
  get "users/:id/profile" => "users#public_profile", as: :public_profile
  post "users/:id/follow" => "users#follow", as: :follow_user
  delete "users/:id/unfollow" => "users#unfollow", as: :unfollow_user

  # photos routes
  get "photos/feed" => "photos#feed", as: :photos_feed
  get "photos/discovery" => "photos#discovery", as: :photos_discovery

  # albums routes
  get "albums/feed" => "albums#feed", as: :albums_feed
  get "albums/discovery" => "albums#discovery", as: :albums_discovery

  resources :albums, only: [ :index, :new, :create, :edit, :update, :destroy ]
  resources :photos, only: [ :index, :new, :create, :edit, :update, :destroy ]
  resources :users, only: [ :index, :create, :new, :update ]

  namespace :admin do
    root "photos#index"
    resources :photos, only: [ :index, :edit, :update ]
    resources :albums, only: [ :index, :edit, :update ]
    resources :users, only: [ :index, :edit, :update, :destroy ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  layout :layout_by_resource

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes

  # Pagy pagination
  include Pagy::Method

  private

  def layout_by_resource
    devise_controller? ? "auth" : "application"
  end

  def authorize_admin!
    redirect_to root_path, alert: "Not authorized" unless current_user&.role_admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
      <div class="container">
        <% if user_signed_in? && current_user.role_admin? %>
          <%= link_to 'Fotobook Admin', admin_root_path, class: "navbar-brand text-light fw-bold fs-3", data: { turbo_prefetch: false } %>
        <% else %>
          <%= link_to 'Fotobook', root_path, class: "navbar-brand text-light fw-bold fs-3", data: { turbo_prefetch: false } %>
        <% end %>

        <form class="d-flex me-auto col-md-5 col-4" role="search">
          <input
            class="form-control"
            type="search"
            placeholder="Search photos / albums"
            aria-label="Search"
          />
        </form>

        <% if user_signed_in? %>
          <div class="d-flex dropdown">
            <a
              class="nav-link fw-bold fs-5 text-light d-flex align-items-center"
              href="#"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <%= image_tag avatar_url(current_user), class: "rounded-circle me-2", style: "width: 40px; height: 40px; object-fit: cover", alt: "Profile Avatar" %>
              <p class="m-0 d-none d-lg-block"><%= current_user.firstName + " " + current_user.lastName %></p>
            </a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
              <li><%= link_to "Profile", profile_path, class: "dropdown-item", data: { turbo_prefetch: false } %></li>
              <li><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item", data: { turbo: false } %></li>
            </ul>
          </div>

        <% else%>
          <%= link_to 'Login', new_user_session_path, class: "nav-link fw-bold fs-5 text-light", "aria-current": "page", data: { turbo_prefetch: false } %>
        <% end %>
      </div>
    </nav>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-md">
            <div class="container-fluid">
              <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="offcanvas"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="navbar-toggler-icon"></span>
              </button>
              <!-- canvas khi về màn hình nhỏ -->
              <div
                class="offcanvas-md offcanvas-start"
                tabindex="-1"
                id="navbarNav"
                aria-labelledby="offcanvasLabel"
              >
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title" id="offcanvasLabel">Menu</h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="offcanvas"
                    data-bs-target="#navbarNav"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav flex-column">
                    <% if current_user.role_admin? %>
                      <li class="nav-item">
                        <%= link_to 'Manage Photos', admin_photos_path, class: "nav-link ", "aria-current": "page", data: { turbo_prefetch: false } %>
                      </li>
                      <li class="nav-item">
                        <%= link_to 'Manage Albums', admin_albums_path, class: "nav-link ", "aria-current": "page", data: { turbo_prefetch: false } %>
                      </li>
                      <li class="nav-item">
                        <%= link_to 'Manage Users', admin_users_path, class: "nav-link ", "aria-current": "page", data: { turbo_prefetch: false } %>
                      </li>
                        
                    <% else %>
                      <li class="nav-item">
                        <%= link_to 'Feeds', controller_name == "photos" ? photos_feed_path : albums_feed_path, class: "nav-link active", "aria-current": "page", data: { turbo_prefetch: false } %>
                      </li>
                      <li class="nav-item">
                        <%= link_to 'Discovery', controller_name == "photos" ? photos_discovery_path : albums_discovery_path, class: "nav-link", data: { turbo_prefetch: false } %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </nav>

app/views/application/_toast.html.erb
<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div
    id="flashToast"
    class="toast align-items-center text-bg-<%= alert.present? ? "danger" : "success" %> border-0"
    role="alert"
    aria-live="assertive"
    aria-atomic="true"
    data-bs-autohide="true"
    data-bs-delay="4000"
  >
    <div class="d-flex">
      <div class="toast-body">
        <% if notice.present? %>
          <div><%= notice %></div>
        <% end %>
        <% if alert.present? %>
          <div><%= alert %></div>
        <% end %>
      </div>
      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
</div>